name: Deploy to EC2

on:
  push:
    branches:
      - master
env:
  AWS_DEFAULT_REGION: ap-northeast-2
  AWS_EC2_METADATA_DISABLED: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@52.79.227.4 "cd /home/ubuntu/build && npm install"
